Repository helium/HIP, pull requests merged in 2020-08, with the labels that each got.

#31 Proportional reward scheme for data transfers
  0010-usage-based-data-transfer-rewards.md
Labels: enhancement

#30 HIP(x): Remote Location Assert
  0010-remote-location-assert.md
Labels: Draft

#33 HIP11: Usage based rewards proposal
  NNNN-usage-based-rewards-structure.md
Labels: draft

#29 DC Expensing Amendment to Charge for ACK frames
  0004-expensing-data-credits-for-lorawan.md
  README.md
Labels: draft
