Repository helium/HIP, pull requests merged in 2022-02, with the labels that each got.

#346 Replace all references to `master` with `main`
  README.md
Labels: bug

#342 Propose PoC targeting based on ledger h3 index
  0054-h3dex-targeting.md
Labels: draft

#357 Mark HIP45 doc as approved
  0045-lorawan-frequency-plan-selection.md
  README.md
Labels: status updates

#358 Mark HIP46 as approved
  0046-lorawan-netid-routing.md
  README.md
Labels: status updates

#366 HIP draft – state channel disputes
  0056-state-channel-dispute-strategy.md
Labels: draft
