Repository helium/HIP, pull requests merged in 2023-12, with the labels that each got.

#819 Heatedlime hip 98 update
  0098-mobile-subdao-quality-of-service-requirements.md
Labels: updates

#827 resolve stray includes
  0073-consensus-deselection-weighting.md
  0073-consensus-deselection-weighting/cg-penalties.png
  0077-solana-parameters.md
  0077-solana-parameters/token-emissions-as-of-solana-migration.pdf
  0093-addition-of-wifi-aps-to-mobile-subdao.md
  0093-addition-of-wifi-aps-to-mobile-subdao/templated_coverage.png
  README.md
Labels: meta-governance

#829 Update README.md for 86/96
  README.md
Labels: meta-governance

#820 HIP 102: Helium Educational LNS - Unrewarded Trial Network
  0102-helium-educational-lns.md
Labels: draft, economic

#822 HIP 103: MOBILE Oracle Hex Boosting
  0103-oracle-hex-boosting.md
Labels: technical, economic

#833 Update HIP 98
  0098-mobile-subdao-quality-of-service-requirements.md
Labels: updates

#830 New HIP proposal - Finetune HIP17 parameters to tackle density
  0000-finetune-hip17-parameters-to-tackle-density/Histogram_of_Res4_Hex_Reward_Units_as-is.png
  0000-finetune-hip17-parameters-to-tackle-density/Histogram_of_Res4_Hex_Reward_Units_test1.png
  0000-finetune-hip17-parameters-to-tackle-density/Histogram_of_Res5_Hex_Reward_Units_as-is.png
  0000-finetune-hip17-parameters-to-tackle-density/Histogram_of_Res5_Hex_Reward_Units_test1.png
  0000-finetune-hip17-parameters-to-tackle-density/bercelona-default.png
  0000-finetune-hip17-parameters-to-tackle-density/bercelona-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/berlin-default.png
  0000-finetune-hip17-parameters-to-tackle-density/berlin-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/budapest-default.png
  0000-finetune-hip17-parameters-to-tackle-density/budapest-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/chicago-default.png
  0000-finetune-hip17-parameters-to-tackle-density/chicago-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/colorado-default.png
  0000-finetune-hip17-parameters-to-tackle-density/colorado-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/dallas-default.png
  0000-finetune-hip17-parameters-to-tackle-density/dallas-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/istanbul-default.png
  0000-finetune-hip17-parameters-to-tackle-density/istanbul-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/la-default.png
  0000-finetune-hip17-parameters-to-tackle-density/la-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/lisbon-default.png
  0000-finetune-hip17-parameters-to-tackle-density/lisbon-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/london-default.png
  0000-finetune-hip17-parameters-to-tackle-density/london-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/madrid-default.png
  0000-finetune-hip17-parameters-to-tackle-density/madrid-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/nyc-default.png
  0000-finetune-hip17-parameters-to-tackle-density/nyc-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/orlando-default.png
  0000-finetune-hip17-parameters-to-tackle-density/orlando-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/paris-default.png
  0000-finetune-hip17-parameters-to-tackle-density/paris-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/philedelphia-default.png
  0000-finetune-hip17-parameters-to-tackle-density/philedelphia-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/portland-default.png
  0000-finetune-hip17-parameters-to-tackle-density/portland-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/rome-default.png
  0000-finetune-hip17-parameters-to-tackle-density/rome-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/rotterdam-default.png
  0000-finetune-hip17-parameters-to-tackle-density/rotterdam-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/sanantonio-default.png
  0000-finetune-hip17-parameters-to-tackle-density/sanantonio-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/seattle-default.png
  0000-finetune-hip17-parameters-to-tackle-density/seattle-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/sf-default.png
  0000-finetune-hip17-parameters-to-tackle-density/sf-res4-boundary.jpg
  0000-finetune-hip17-parameters-to-tackle-density/sf-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/toronto-default.png
  0000-finetune-hip17-parameters-to-tackle-density/toronto-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/vienna-default.png
  0000-finetune-hip17-parameters-to-tackle-density/vienna-t1.png
  0000-finetune-hip17-parameters-to-tackle-density/washington-default.png
  0000-finetune-hip17-parameters-to-tackle-density/washington-t1.png
  0104-finetune-hip17-parameters-to-tackle-density.md
Labels: technical

#821 HIP 105: Modification of MOBILE subDAO Hex Limits
  0105-modification-of-mobile-subdao-hex-limits.md
Labels: technical, economic

#845 HIP 101: Updating the title to more accurately reflect the spirit of the HIP
  0101-equalizing-poc-rewards-across-wifi-and-cbrs.md
Labels: updates

#846 Fix misprint in HIP-102 "disllowment" -> "disallowment"
  0102-helium-educational-lns.md
Labels: updates
