Repository helium/HIP, pull requests merged in 2024-03, with the labels that each got.

#925 HIP 110: Proxy Voting
  0110-proxy-voting.md
  README.md
Labels: meta-governance, IOT, MOBILE, HNT

#903 HIP 111: MOBILE Data Utility Benchmark - 10x Reward Boost
  0111-mobile-data-utility-benchmark.md
Labels: draft, technical, economic, MOBILE

#912 HIP 112: Scaling IOT Hotspot Assert Fees
  0112-scaling-iot-location-assert-fees.md
Labels: updates, technical, economic, IOT

#924 HIP 113: Reward CBRS As Experimental
  0113-reward-cbrs-as-experimental.md
Labels: economic, MOBILE

#927 HIP 114: Incentive Escrow Fund for Subscriber Referrals
  0114-incentive-escrow-fund-for-subscriber-referrals.md
Labels: idea, technical, economic, MOBILE

#921 HIP 115: Redefining the MOBILE Maker Approval Process
  0115-redefining-the-mobile-maker-approval-process.md
Labels: draft, idea, updates, technical, economic, MOBILE

#948 HIP 116: OUI Additional Address Space Reshuffle
  0116-oui-additional-address-space-reshuffle.md
Labels: technical, economic, IOT

#950 HIP 118: Verification Mapping for MOBILE Network
  0118-verification-mapping.md
Labels: technical, economic, MOBILE
