Repository helium/HIP, pull requests merged in 2024-05, with the labels that each got.

#1006 HIP 123: Redefining IOT Data-Only Hotspot Onboarding and Assertion Fees
  0123-redefining-data-only-onboarding-and-assertion-fees.md
Labels: technical, economic, IOT

#1011 HIP 124: Securing IOT Governance Through Staking Rewards
  0124-securing-iot-governance-through-staking-rewards.md
Labels: economic, governance, IOT

#1017 HIP 125: Temporary Anti-Gaming Measures For Boosted Hexes
  0125-temporary-anti-gaming-measures-for-boosted-hexes.md
Labels: updates, technical, economic, MOBILE
