Repository helium/HIP, pull requests merged in 2024-01, with the labels that each got.

#860 HIP 101: Final Updates
  0101-equalizing-poc-rewards-across-wifi-and-cbrs.md
Labels: updates

#867 Updated 104 for IOT specific and HIP17 references.
  0104-finetune-hip17-parameters-to-tackle-density.md
Labels: amendment

#869 Missing > in HIP 104 table
  0104-finetune-hip17-parameters-to-tackle-density.md
Labels: amendment

#828 HIP 106: Hotspot Bidirectional Coverage Requirement
  0106-hotspot-bidirectional-coverage-requirement.md
Labels: idea, technical

#872 Updated Readme with all deployed HIPs
  README.md
Labels: amendment

#874 HIP 103: Updates
  0103-oracle-hex-boosting.md
Labels: amendment, updates

#873 HIP 98: Updates
  0098-mobile-subdao-quality-of-service-requirements.md
Labels: amendment, updates

#875 HIP 103: Updates to the timeline and roadmap
  0103-oracle-hex-boosting.md
Labels: amendment

#880 HIP 105: Remove CBRS Limits
  0105-modification-of-mobile-subdao-hex-limits.md
Labels: amendment

#879 HIP 103: Updates for footfall oracles and cleanup
  0103-oracle-hex-boosting.md
Labels: amendment

#857 HIP 107: Deterring Gaming Through Verification Fees
  0107-deterring-gaming-through-verification-fees.md
Labels: idea, technical, economic, MOBILE
